Fix assignment to unbound variable
When specifying `is_balanced=True`, we get the following error:

```
UnboundLocalError: local variable 'dates' referenced before assignment
```

This happens because `dates` is defined only in not balanced case. Fix:
define it in balanced case too.